/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuestoesRouteImport } from './routes/questoes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EditalRouteImport } from './routes/edital'
import { Route as CronogramaRouteImport } from './routes/cronograma'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAnalyzeQuestionRouteImport } from './routes/api/analyze-question'

const QuestoesRoute = QuestoesRouteImport.update({
  id: '/questoes',
  path: '/questoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EditalRoute = EditalRouteImport.update({
  id: '/edital',
  path: '/edital',
  getParentRoute: () => rootRouteImport,
} as any)
const CronogramaRoute = CronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeQuestionRoute = ApiAnalyzeQuestionRouteImport.update({
  id: '/api/analyze-question',
  path: '/api/analyze-question',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cronograma': typeof CronogramaRoute
  '/edital': typeof EditalRoute
  '/login': typeof LoginRoute
  '/questoes': typeof QuestoesRoute
  '/api/analyze-question': typeof ApiAnalyzeQuestionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cronograma': typeof CronogramaRoute
  '/edital': typeof EditalRoute
  '/login': typeof LoginRoute
  '/questoes': typeof QuestoesRoute
  '/api/analyze-question': typeof ApiAnalyzeQuestionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cronograma': typeof CronogramaRoute
  '/edital': typeof EditalRoute
  '/login': typeof LoginRoute
  '/questoes': typeof QuestoesRoute
  '/api/analyze-question': typeof ApiAnalyzeQuestionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cronograma'
    | '/edital'
    | '/login'
    | '/questoes'
    | '/api/analyze-question'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cronograma'
    | '/edital'
    | '/login'
    | '/questoes'
    | '/api/analyze-question'
  id:
    | '__root__'
    | '/'
    | '/cronograma'
    | '/edital'
    | '/login'
    | '/questoes'
    | '/api/analyze-question'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CronogramaRoute: typeof CronogramaRoute
  EditalRoute: typeof EditalRoute
  LoginRoute: typeof LoginRoute
  QuestoesRoute: typeof QuestoesRoute
  ApiAnalyzeQuestionRoute: typeof ApiAnalyzeQuestionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/questoes': {
      id: '/questoes'
      path: '/questoes'
      fullPath: '/questoes'
      preLoaderRoute: typeof QuestoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edital': {
      id: '/edital'
      path: '/edital'
      fullPath: '/edital'
      preLoaderRoute: typeof EditalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronograma': {
      id: '/cronograma'
      path: '/cronograma'
      fullPath: '/cronograma'
      preLoaderRoute: typeof CronogramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-question': {
      id: '/api/analyze-question'
      path: '/api/analyze-question'
      fullPath: '/api/analyze-question'
      preLoaderRoute: typeof ApiAnalyzeQuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CronogramaRoute: CronogramaRoute,
  EditalRoute: EditalRoute,
  LoginRoute: LoginRoute,
  QuestoesRoute: QuestoesRoute,
  ApiAnalyzeQuestionRoute: ApiAnalyzeQuestionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
